FROM php:5.6.32-fpm
LABEL maintainer="PHP:5.6"

RUN apt-get update \
  && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev \
  && docker-php-source extract \
  && docker-php-ext-install -j$(nproc) mysqli pdo_mysql sockets bcmath calendar gettext pcntl shmop sysvsem exif zip mcrypt \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install -j$(nproc) gd \
  && docker-php-source delete
